theme: jekyll-theme-cayman
highlighter: rouge
encoding: bom|utf-8
name: Blackkadder personal site
author: Blackkadder
url: https://blackkadder.github.io/
project-name: Blackkadder portfolio
title: Blackkadder portfolio
description: Collection of code
